// Code generated by pegomock. DO NOT EDIT.
package matchers

import (
	"reflect"
	"github.com/petergtz/pegomock"
	http "net/http"
)

func AnyPtrToHttpResponse() *http.Response {
	pegomock.RegisterMatcher(pegomock.NewAnyMatcher(reflect.TypeOf((*(*http.Response))(nil)).Elem()))
	var nullValue *http.Response
	return nullValue
}

func EqPtrToHttpResponse(value *http.Response) *http.Response {
	pegomock.RegisterMatcher(&pegomock.EqMatcher{Value: value})
	var nullValue *http.Response
	return nullValue
}
