// Code generated by pegomock. DO NOT EDIT.
package matchers

import (
	"reflect"
	"github.com/petergtz/pegomock"
	time "time"
)

func AnyTimeDuration() time.Duration {
	pegomock.RegisterMatcher(pegomock.NewAnyMatcher(reflect.TypeOf((*(time.Duration))(nil)).Elem()))
	var nullValue time.Duration
	return nullValue
}

func EqTimeDuration(value time.Duration) time.Duration {
	pegomock.RegisterMatcher(&pegomock.EqMatcher{Value: value})
	var nullValue time.Duration
	return nullValue
}
