// Automatically generated by pegomock. DO NOT EDIT!
// Source: github.com/petergtz/bitsgo (interfaces: Blobstore)

package main_test

import (
	io "io"
	http "net/http"
	"reflect"

	pegomock "github.com/petergtz/pegomock"
)

type MockBlobstore struct {
	fail func(message string, callerSkip ...int)
}

func NewMockBlobstore() *MockBlobstore {
	return &MockBlobstore{fail: pegomock.GlobalFailHandler}
}

func (mock *MockBlobstore) Get(path string, responseWriter http.ResponseWriter) {
	params := []pegomock.Param{path, responseWriter}
	pegomock.GetGenericMockFrom(mock).Invoke("Get", params, []reflect.Type{})
}

func (mock *MockBlobstore) Put(path string, src io.ReadSeeker, responseWriter http.ResponseWriter) {
	params := []pegomock.Param{path, src, responseWriter}
	pegomock.GetGenericMockFrom(mock).Invoke("Put", params, []reflect.Type{})
}

func (mock *MockBlobstore) VerifyWasCalledOnce() *VerifierBlobstore {
	return &VerifierBlobstore{mock, pegomock.Times(1), nil}
}

func (mock *MockBlobstore) VerifyWasCalled(invocationCountMatcher pegomock.Matcher) *VerifierBlobstore {
	return &VerifierBlobstore{mock, invocationCountMatcher, nil}
}

func (mock *MockBlobstore) VerifyWasCalledInOrder(invocationCountMatcher pegomock.Matcher, inOrderContext *pegomock.InOrderContext) *VerifierBlobstore {
	return &VerifierBlobstore{mock, invocationCountMatcher, inOrderContext}
}

type VerifierBlobstore struct {
	mock                   *MockBlobstore
	invocationCountMatcher pegomock.Matcher
	inOrderContext         *pegomock.InOrderContext
}

func (verifier *VerifierBlobstore) Get(path string, responseWriter http.ResponseWriter) *Blobstore_Get_OngoingVerification {
	params := []pegomock.Param{path, responseWriter}
	methodInvocations := pegomock.GetGenericMockFrom(verifier.mock).Verify(verifier.inOrderContext, verifier.invocationCountMatcher, "Get", params)
	return &Blobstore_Get_OngoingVerification{mock: verifier.mock, methodInvocations: methodInvocations}
}

type Blobstore_Get_OngoingVerification struct {
	mock              *MockBlobstore
	methodInvocations []pegomock.MethodInvocation
}

func (c *Blobstore_Get_OngoingVerification) GetCapturedArguments() (string, http.ResponseWriter) {
	path, responseWriter := c.GetAllCapturedArguments()
	return path[len(path)-1], responseWriter[len(responseWriter)-1]
}

func (c *Blobstore_Get_OngoingVerification) GetAllCapturedArguments() (_param0 []string, _param1 []http.ResponseWriter) {
	params := pegomock.GetGenericMockFrom(c.mock).GetInvocationParams(c.methodInvocations)
	if len(params) > 0 {
		_param0 = make([]string, len(params[0]))
		for u, param := range params[0] {
			_param0[u] = param.(string)
		}
		_param1 = make([]http.ResponseWriter, len(params[1]))
		for u, param := range params[1] {
			_param1[u] = param.(http.ResponseWriter)
		}
	}
	return
}

func (verifier *VerifierBlobstore) Put(path string, src io.ReadSeeker, responseWriter http.ResponseWriter) *Blobstore_Put_OngoingVerification {
	params := []pegomock.Param{path, src, responseWriter}
	methodInvocations := pegomock.GetGenericMockFrom(verifier.mock).Verify(verifier.inOrderContext, verifier.invocationCountMatcher, "Put", params)
	return &Blobstore_Put_OngoingVerification{mock: verifier.mock, methodInvocations: methodInvocations}
}

type Blobstore_Put_OngoingVerification struct {
	mock              *MockBlobstore
	methodInvocations []pegomock.MethodInvocation
}

func (c *Blobstore_Put_OngoingVerification) GetCapturedArguments() (string, io.ReadSeeker, http.ResponseWriter) {
	path, src, responseWriter := c.GetAllCapturedArguments()
	return path[len(path)-1], src[len(src)-1], responseWriter[len(responseWriter)-1]
}

func (c *Blobstore_Put_OngoingVerification) GetAllCapturedArguments() (_param0 []string, _param1 []io.ReadSeeker, _param2 []http.ResponseWriter) {
	params := pegomock.GetGenericMockFrom(c.mock).GetInvocationParams(c.methodInvocations)
	if len(params) > 0 {
		_param0 = make([]string, len(params[0]))
		for u, param := range params[0] {
			_param0[u] = param.(string)
		}
		_param1 = make([]io.ReadSeeker, len(params[1]))
		for u, param := range params[1] {
			_param1[u] = param.(io.ReadSeeker)
		}
		_param2 = make([]http.ResponseWriter, len(params[2]))
		for u, param := range params[2] {
			_param2[u] = param.(http.ResponseWriter)
		}
	}
	return
}
