// Automatically generated by pegomock. DO NOT EDIT!
// Source: github.com/petergtz/bitsgo (interfaces: Blobstore)

package bitsgo_test

import (
	pegomock "github.com/petergtz/pegomock"
	io "io"
	"reflect"
)

type MockBlobstore struct {
	fail func(message string, callerSkip ...int)
}

func NewMockBlobstore() *MockBlobstore {
	return &MockBlobstore{fail: pegomock.GlobalFailHandler}
}

func (mock *MockBlobstore) Copy(_param0 string, _param1 string) error {
	params := []pegomock.Param{_param0, _param1}
	result := pegomock.GetGenericMockFrom(mock).Invoke("Copy", params, []reflect.Type{reflect.TypeOf((*error)(nil)).Elem()})
	var ret0 error
	if len(result) != 0 {
		if result[0] != nil {
			ret0 = result[0].(error)
		}
	}
	return ret0
}

func (mock *MockBlobstore) Delete(_param0 string) error {
	params := []pegomock.Param{_param0}
	result := pegomock.GetGenericMockFrom(mock).Invoke("Delete", params, []reflect.Type{reflect.TypeOf((*error)(nil)).Elem()})
	var ret0 error
	if len(result) != 0 {
		if result[0] != nil {
			ret0 = result[0].(error)
		}
	}
	return ret0
}

func (mock *MockBlobstore) DeleteDir(_param0 string) error {
	params := []pegomock.Param{_param0}
	result := pegomock.GetGenericMockFrom(mock).Invoke("DeleteDir", params, []reflect.Type{reflect.TypeOf((*error)(nil)).Elem()})
	var ret0 error
	if len(result) != 0 {
		if result[0] != nil {
			ret0 = result[0].(error)
		}
	}
	return ret0
}

func (mock *MockBlobstore) Exists(_param0 string) (bool, error) {
	params := []pegomock.Param{_param0}
	result := pegomock.GetGenericMockFrom(mock).Invoke("Exists", params, []reflect.Type{reflect.TypeOf((*bool)(nil)).Elem(), reflect.TypeOf((*error)(nil)).Elem()})
	var ret0 bool
	var ret1 error
	if len(result) != 0 {
		if result[0] != nil {
			ret0 = result[0].(bool)
		}
		if result[1] != nil {
			ret1 = result[1].(error)
		}
	}
	return ret0, ret1
}

func (mock *MockBlobstore) GetOrRedirect(_param0 string) (io.ReadCloser, string, error) {
	params := []pegomock.Param{_param0}
	result := pegomock.GetGenericMockFrom(mock).Invoke("GetOrRedirect", params, []reflect.Type{reflect.TypeOf((*io.ReadCloser)(nil)).Elem(), reflect.TypeOf((*string)(nil)).Elem(), reflect.TypeOf((*error)(nil)).Elem()})
	var ret0 io.ReadCloser
	var ret1 string
	var ret2 error
	if len(result) != 0 {
		if result[0] != nil {
			ret0 = result[0].(io.ReadCloser)
		}
		if result[1] != nil {
			ret1 = result[1].(string)
		}
		if result[2] != nil {
			ret2 = result[2].(error)
		}
	}
	return ret0, ret1, ret2
}

func (mock *MockBlobstore) HeadOrRedirectAsGet(_param0 string) (string, error) {
	params := []pegomock.Param{_param0}
	result := pegomock.GetGenericMockFrom(mock).Invoke("HeadOrRedirectAsGet", params, []reflect.Type{reflect.TypeOf((*string)(nil)).Elem(), reflect.TypeOf((*error)(nil)).Elem()})
	var ret0 string
	var ret1 error
	if len(result) != 0 {
		if result[0] != nil {
			ret0 = result[0].(string)
		}
		if result[1] != nil {
			ret1 = result[1].(error)
		}
	}
	return ret0, ret1
}

func (mock *MockBlobstore) Put(_param0 string, _param1 io.ReadSeeker) error {
	params := []pegomock.Param{_param0, _param1}
	result := pegomock.GetGenericMockFrom(mock).Invoke("Put", params, []reflect.Type{reflect.TypeOf((*error)(nil)).Elem()})
	var ret0 error
	if len(result) != 0 {
		if result[0] != nil {
			ret0 = result[0].(error)
		}
	}
	return ret0
}

func (mock *MockBlobstore) VerifyWasCalledOnce() *VerifierBlobstore {
	return &VerifierBlobstore{mock, pegomock.Times(1), nil}
}

func (mock *MockBlobstore) VerifyWasCalled(invocationCountMatcher pegomock.Matcher) *VerifierBlobstore {
	return &VerifierBlobstore{mock, invocationCountMatcher, nil}
}

func (mock *MockBlobstore) VerifyWasCalledInOrder(invocationCountMatcher pegomock.Matcher, inOrderContext *pegomock.InOrderContext) *VerifierBlobstore {
	return &VerifierBlobstore{mock, invocationCountMatcher, inOrderContext}
}

type VerifierBlobstore struct {
	mock                   *MockBlobstore
	invocationCountMatcher pegomock.Matcher
	inOrderContext         *pegomock.InOrderContext
}

func (verifier *VerifierBlobstore) Copy(_param0 string, _param1 string) *Blobstore_Copy_OngoingVerification {
	params := []pegomock.Param{_param0, _param1}
	methodInvocations := pegomock.GetGenericMockFrom(verifier.mock).Verify(verifier.inOrderContext, verifier.invocationCountMatcher, "Copy", params)
	return &Blobstore_Copy_OngoingVerification{mock: verifier.mock, methodInvocations: methodInvocations}
}

type Blobstore_Copy_OngoingVerification struct {
	mock              *MockBlobstore
	methodInvocations []pegomock.MethodInvocation
}

func (c *Blobstore_Copy_OngoingVerification) GetCapturedArguments() (string, string) {
	_param0, _param1 := c.GetAllCapturedArguments()
	return _param0[len(_param0)-1], _param1[len(_param1)-1]
}

func (c *Blobstore_Copy_OngoingVerification) GetAllCapturedArguments() (_param0 []string, _param1 []string) {
	params := pegomock.GetGenericMockFrom(c.mock).GetInvocationParams(c.methodInvocations)
	if len(params) > 0 {
		_param0 = make([]string, len(params[0]))
		for u, param := range params[0] {
			_param0[u] = param.(string)
		}
		_param1 = make([]string, len(params[1]))
		for u, param := range params[1] {
			_param1[u] = param.(string)
		}
	}
	return
}

func (verifier *VerifierBlobstore) Delete(_param0 string) *Blobstore_Delete_OngoingVerification {
	params := []pegomock.Param{_param0}
	methodInvocations := pegomock.GetGenericMockFrom(verifier.mock).Verify(verifier.inOrderContext, verifier.invocationCountMatcher, "Delete", params)
	return &Blobstore_Delete_OngoingVerification{mock: verifier.mock, methodInvocations: methodInvocations}
}

type Blobstore_Delete_OngoingVerification struct {
	mock              *MockBlobstore
	methodInvocations []pegomock.MethodInvocation
}

func (c *Blobstore_Delete_OngoingVerification) GetCapturedArguments() string {
	_param0 := c.GetAllCapturedArguments()
	return _param0[len(_param0)-1]
}

func (c *Blobstore_Delete_OngoingVerification) GetAllCapturedArguments() (_param0 []string) {
	params := pegomock.GetGenericMockFrom(c.mock).GetInvocationParams(c.methodInvocations)
	if len(params) > 0 {
		_param0 = make([]string, len(params[0]))
		for u, param := range params[0] {
			_param0[u] = param.(string)
		}
	}
	return
}

func (verifier *VerifierBlobstore) DeleteDir(_param0 string) *Blobstore_DeleteDir_OngoingVerification {
	params := []pegomock.Param{_param0}
	methodInvocations := pegomock.GetGenericMockFrom(verifier.mock).Verify(verifier.inOrderContext, verifier.invocationCountMatcher, "DeleteDir", params)
	return &Blobstore_DeleteDir_OngoingVerification{mock: verifier.mock, methodInvocations: methodInvocations}
}

type Blobstore_DeleteDir_OngoingVerification struct {
	mock              *MockBlobstore
	methodInvocations []pegomock.MethodInvocation
}

func (c *Blobstore_DeleteDir_OngoingVerification) GetCapturedArguments() string {
	_param0 := c.GetAllCapturedArguments()
	return _param0[len(_param0)-1]
}

func (c *Blobstore_DeleteDir_OngoingVerification) GetAllCapturedArguments() (_param0 []string) {
	params := pegomock.GetGenericMockFrom(c.mock).GetInvocationParams(c.methodInvocations)
	if len(params) > 0 {
		_param0 = make([]string, len(params[0]))
		for u, param := range params[0] {
			_param0[u] = param.(string)
		}
	}
	return
}

func (verifier *VerifierBlobstore) Exists(_param0 string) *Blobstore_Exists_OngoingVerification {
	params := []pegomock.Param{_param0}
	methodInvocations := pegomock.GetGenericMockFrom(verifier.mock).Verify(verifier.inOrderContext, verifier.invocationCountMatcher, "Exists", params)
	return &Blobstore_Exists_OngoingVerification{mock: verifier.mock, methodInvocations: methodInvocations}
}

type Blobstore_Exists_OngoingVerification struct {
	mock              *MockBlobstore
	methodInvocations []pegomock.MethodInvocation
}

func (c *Blobstore_Exists_OngoingVerification) GetCapturedArguments() string {
	_param0 := c.GetAllCapturedArguments()
	return _param0[len(_param0)-1]
}

func (c *Blobstore_Exists_OngoingVerification) GetAllCapturedArguments() (_param0 []string) {
	params := pegomock.GetGenericMockFrom(c.mock).GetInvocationParams(c.methodInvocations)
	if len(params) > 0 {
		_param0 = make([]string, len(params[0]))
		for u, param := range params[0] {
			_param0[u] = param.(string)
		}
	}
	return
}

func (verifier *VerifierBlobstore) GetOrRedirect(_param0 string) *Blobstore_GetOrRedirect_OngoingVerification {
	params := []pegomock.Param{_param0}
	methodInvocations := pegomock.GetGenericMockFrom(verifier.mock).Verify(verifier.inOrderContext, verifier.invocationCountMatcher, "GetOrRedirect", params)
	return &Blobstore_GetOrRedirect_OngoingVerification{mock: verifier.mock, methodInvocations: methodInvocations}
}

type Blobstore_GetOrRedirect_OngoingVerification struct {
	mock              *MockBlobstore
	methodInvocations []pegomock.MethodInvocation
}

func (c *Blobstore_GetOrRedirect_OngoingVerification) GetCapturedArguments() string {
	_param0 := c.GetAllCapturedArguments()
	return _param0[len(_param0)-1]
}

func (c *Blobstore_GetOrRedirect_OngoingVerification) GetAllCapturedArguments() (_param0 []string) {
	params := pegomock.GetGenericMockFrom(c.mock).GetInvocationParams(c.methodInvocations)
	if len(params) > 0 {
		_param0 = make([]string, len(params[0]))
		for u, param := range params[0] {
			_param0[u] = param.(string)
		}
	}
	return
}

func (verifier *VerifierBlobstore) HeadOrRedirectAsGet(_param0 string) *Blobstore_HeadOrRedirectAsGet_OngoingVerification {
	params := []pegomock.Param{_param0}
	methodInvocations := pegomock.GetGenericMockFrom(verifier.mock).Verify(verifier.inOrderContext, verifier.invocationCountMatcher, "HeadOrRedirectAsGet", params)
	return &Blobstore_HeadOrRedirectAsGet_OngoingVerification{mock: verifier.mock, methodInvocations: methodInvocations}
}

type Blobstore_HeadOrRedirectAsGet_OngoingVerification struct {
	mock              *MockBlobstore
	methodInvocations []pegomock.MethodInvocation
}

func (c *Blobstore_HeadOrRedirectAsGet_OngoingVerification) GetCapturedArguments() string {
	_param0 := c.GetAllCapturedArguments()
	return _param0[len(_param0)-1]
}

func (c *Blobstore_HeadOrRedirectAsGet_OngoingVerification) GetAllCapturedArguments() (_param0 []string) {
	params := pegomock.GetGenericMockFrom(c.mock).GetInvocationParams(c.methodInvocations)
	if len(params) > 0 {
		_param0 = make([]string, len(params[0]))
		for u, param := range params[0] {
			_param0[u] = param.(string)
		}
	}
	return
}

func (verifier *VerifierBlobstore) Put(_param0 string, _param1 io.ReadSeeker) *Blobstore_Put_OngoingVerification {
	params := []pegomock.Param{_param0, _param1}
	methodInvocations := pegomock.GetGenericMockFrom(verifier.mock).Verify(verifier.inOrderContext, verifier.invocationCountMatcher, "Put", params)
	return &Blobstore_Put_OngoingVerification{mock: verifier.mock, methodInvocations: methodInvocations}
}

type Blobstore_Put_OngoingVerification struct {
	mock              *MockBlobstore
	methodInvocations []pegomock.MethodInvocation
}

func (c *Blobstore_Put_OngoingVerification) GetCapturedArguments() (string, io.ReadSeeker) {
	_param0, _param1 := c.GetAllCapturedArguments()
	return _param0[len(_param0)-1], _param1[len(_param1)-1]
}

func (c *Blobstore_Put_OngoingVerification) GetAllCapturedArguments() (_param0 []string, _param1 []io.ReadSeeker) {
	params := pegomock.GetGenericMockFrom(c.mock).GetInvocationParams(c.methodInvocations)
	if len(params) > 0 {
		_param0 = make([]string, len(params[0]))
		for u, param := range params[0] {
			_param0[u] = param.(string)
		}
		_param1 = make([]io.ReadSeeker, len(params[1]))
		for u, param := range params[1] {
			_param1[u] = param.(io.ReadSeeker)
		}
	}
	return
}
