// Code generated by pegomock. DO NOT EDIT.
// Source: github.com/petergtz/bitsgo/ccupdater (interfaces: HttpClient)

package ccupdater_test

import (
	pegomock "github.com/petergtz/pegomock"
	http "net/http"
	"reflect"
)

type MockHttpClient struct {
	fail func(message string, callerSkip ...int)
}

func NewMockHttpClient() *MockHttpClient {
	return &MockHttpClient{fail: pegomock.GlobalFailHandler}
}

func (mock *MockHttpClient) Do(_param0 *http.Request) (*http.Response, error) {
	params := []pegomock.Param{_param0}
	result := pegomock.GetGenericMockFrom(mock).Invoke("Do", params, []reflect.Type{reflect.TypeOf((**http.Response)(nil)).Elem(), reflect.TypeOf((*error)(nil)).Elem()})
	var ret0 *http.Response
	var ret1 error
	if len(result) != 0 {
		if result[0] != nil {
			ret0 = result[0].(*http.Response)
		}
		if result[1] != nil {
			ret1 = result[1].(error)
		}
	}
	return ret0, ret1
}

func (mock *MockHttpClient) VerifyWasCalledOnce() *VerifierHttpClient {
	return &VerifierHttpClient{mock, pegomock.Times(1), nil}
}

func (mock *MockHttpClient) VerifyWasCalled(invocationCountMatcher pegomock.Matcher) *VerifierHttpClient {
	return &VerifierHttpClient{mock, invocationCountMatcher, nil}
}

func (mock *MockHttpClient) VerifyWasCalledInOrder(invocationCountMatcher pegomock.Matcher, inOrderContext *pegomock.InOrderContext) *VerifierHttpClient {
	return &VerifierHttpClient{mock, invocationCountMatcher, inOrderContext}
}

type VerifierHttpClient struct {
	mock                   *MockHttpClient
	invocationCountMatcher pegomock.Matcher
	inOrderContext         *pegomock.InOrderContext
}

func (verifier *VerifierHttpClient) Do(_param0 *http.Request) *HttpClient_Do_OngoingVerification {
	params := []pegomock.Param{_param0}
	methodInvocations := pegomock.GetGenericMockFrom(verifier.mock).Verify(verifier.inOrderContext, verifier.invocationCountMatcher, "Do", params)
	return &HttpClient_Do_OngoingVerification{mock: verifier.mock, methodInvocations: methodInvocations}
}

type HttpClient_Do_OngoingVerification struct {
	mock              *MockHttpClient
	methodInvocations []pegomock.MethodInvocation
}

func (c *HttpClient_Do_OngoingVerification) GetCapturedArguments() *http.Request {
	_param0 := c.GetAllCapturedArguments()
	return _param0[len(_param0)-1]
}

func (c *HttpClient_Do_OngoingVerification) GetAllCapturedArguments() (_param0 []*http.Request) {
	params := pegomock.GetGenericMockFrom(c.mock).GetInvocationParams(c.methodInvocations)
	if len(params) > 0 {
		_param0 = make([]*http.Request, len(params[0]))
		for u, param := range params[0] {
			_param0[u] = param.(*http.Request)
		}
	}
	return
}
