# frozen_string_literal: true

source 'https://rubygems.org'

# Middleman
gem 'middleman', '~>4.1.0'
gem 'middleman-autoprefixer', '~> 2.7.0'
gem 'middleman-sprockets', '~> 4.0.0'
gem 'middleman-syntax', '~> 3.0.0'
gem 'redcarpet', '~> 3.3.2'
gem 'rouge', '~> 2.0.5'
